@extends('layouts.master3')
@section('halaman3')
<!DOCTYPE html>
<html>
<head>
	<title></title>
</head>

<body>
<ol>Nama-Nama Deck
<li>Giant</li>
<li>Archer</li>
<li>Goblin</li>
<li>Spear_Goblin</li>
<li>Arrows</li>
<li>Giant_Skeleton</li>
<li>Fire_Ball</li>
<li>Lightning</li>
<li>Barbarians</li>
<li>Elite_Barbarians</li>
<li>Rocket</li>
<li>Skeleton_Army</li>
<li>Bomb_Tower</li>
<li>Cannon</li>
<li>Hiden_Tesla</li>
<li>Tombstone</li>
<li>Skeleton</li>
<li>Goblin_Gangk</li>
<li>Lava_Hound</li>
<li>Browler</li>
<li>Princess</li>
<li>Sparky</li>
<li>Miner</li>
<li>Witch</li>
<li>Nigth_Witch</li>
<li>Ghost</li>
<li>Mega_Knight</li>
<li>Mega_Minion</li>
<li>Minions</li>
<li>Inferno_Tower</li>
<li>P.E.K.K.A</li>
<li>Mini_P.E.K.K.A</li>
<li>Baby_Dragon</li>
<li>The_Log</li>
<li>Hog_Rider</li>
<li>Ballon</li>
<li>Goblin_Hut</li>
<li>Barbarian_Hut</li>
<li>Wizard</li>
<li>Ice_Wizard</li>
<li>Electro_Wizard</li>
<li>Bandit</li>
<li>Musketeer</li>
<li>Three_Musketeer</li>
<li>Tornado</li>
<li>Goblin_Barrel</li>
<li>Poison</li>
<li>Lumberjack</li>
<li>Freeze</li>
<li>Clone</li>
<li>Mirror</li>
<li>Bats</li>
<li>Inferno_Dragon</li>
<li>Minion_Horde</li>
</ol>

</body>
</html>

@endsection